version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

parameters:
  run_deployment_workflow:
    type: boolean
    default: True

# ----- STEPS -----
commands:
  step_print_gcp_func_name:
    steps:
      - run:
          name: Print GCP function name
          command: echo Function name - $GCP_FUNCTION
  step_print_gcp_info:
    steps:
      - step_print_gcp_func_name
      - run:
          name: Print GCP project name
          command: echo GCP project - $GCP_PROJECT
          no_output_timeout: 2m
  step_show_working_dir:
    steps:
      - run:
          name: Show working dir
          command: ls -la

# ----- EXECUTORS -----
executors:
  tests:
    docker:
      - image: circleci/python:3.7

# ----- JOBS -----
jobs:
  unittests:
    executor: tests
    steps:
      - checkout
      - run:
          name: Print Current Build Number
          command: echo $CIRCLE_BUILD_NUM
      - run:
          name: Run unittests
          command: python -m unittest


# ----- WORKFLOWS -----
workflows:
 version: 2
 tests:
   jobs:
     - unittests

 deployment:
   when: << pipeline.parameters.run_deployment_workflow >>
   jobs:
     - step_print_gcp_info:
         context: wf_dev
         filters:
           branches:
             only:
               - dev
               - qa
     - step_show_working_dir:
         requires:
           - step_print_gcp_info
         filters:
           branches:
             only:
               - dev

# ----- DEV PIPELINE -----